### PR TITLE
[BUGFIX] #42: exception when editing a tag or author

### LINKED ISSUE #42: slug field in records causes exceptions
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v8.7 LTS
* [x] Can you reproduce the problem on TYPO3 v9.5 LTS
* [x] Did you [perform a cursory search](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3ATYPO3GmbH%2Fblog) to see if your bug or feature is already reported?

## Description

Sometimes when editing a tag an exceptions happens. Condition for the exception is that the page with the same uid as the tag uid does not exist.

Exception message: `#1534710048 TYPO3\CMS\Core\Exception\SiteNotFoundException. No pseudo-site found in root line of page 255`

Stack trace:
in /home/app/web/typo3/sysext/core/Classes/Site/PseudoSiteFinder.php line 179
at TYPO3\CMS\Core\Site\PseudoSiteFinder->getSiteByPageId(255, array())
in /home/app/web/typo3/sysext/core/Classes/Routing/SiteMatcher.php line 210
at TYPO3\CMS\Core\Routing\SiteMatcher->matchByPageId(255)
in /home/app/web/typo3/sysext/core/Classes/Compatibility/PseudoSiteTcaDisplayCondition.php line 79
at TYPO3\CMS\Core\Compatibility\PseudoSiteTcaDisplayCondition->isInPseudoSite(...)

The reason for this is that `PseudoSiteTcaDisplayCondition` is for `pages` table only. It cannot be used for any other types of record. It is quite clear from the comment at the top of the class:

> A display condition that returns true if the page we are dealing with is in a page tree that is represented by a PseudoSite object.
>
> This is used to suppress the 'slug' field in pseudo site page trees when editing page records and to show the alias field.

## Steps to Reproduce

1. Make sure that a tag has uid and there is no page with such uid in the installation
2. Try to edit the tag

**Expected behavior:** Tag can be edited

**Actual behavior:** Exception as described above

## Versions

TYPO3 9.5.5
blog: 9.1.1

### PR DESCRIPTION
**Pull request by dmitryd**
Fixes #42 by removing wrong `displayCond`.

### CODE REVIEW

**Comment by benjaminkott** [comment]
@NeoBlack I need your opinion on this one. I could reproduce the issue if I add a storage folder outside the root and then add authors etc to it. Opening the record again will produce the error @dmitryd described. I am not sure if we should handle this at all, because I am unaware of possible side-effects, with duplicate slug entries for example.

**Comment by NeoBlack** [comment]
As described in the issue, the display condition is for pages only, so for me, it was a mistake to use this display condition for tags and categories.
I guess we should accept this PR and if other errors occur we have to think about a solution, e.g. with an own display condition class.

**Comment by benjaminkott** [comment]
@NeoBlack I´ve may found an issue in the `PseudoSiteTcaDisplayCondition` it fails for all not translatable records that are out of a site. I´ve marked the point where it fails. https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Classes/Compatibility/PseudoSiteTcaDisplayCondition.php#L61-L66

**Comment by dmitryd** [comment]
@benjaminkott 

> I am not sure if we should handle this at all, because I am unaware of possible side-effects, with duplicate slug entries for example.

You should because:
- displayCond is for pages only
- having a blog folder outside of the root is a use case for several sites sharing the same blog entries

**Comment by benjaminkott** [comment]
I´ve thought a lot about this issue, tested a lot and talked a lot about with different persons. Removing the condition seems to be the best option we have after all. It does not make it worse or solved the initial intend. But it´s at least avoiding the exception. We will reconsider it when we have a better solution.

**Pull request merged**
