### PR TITLE
[BUGFIX] Remove outdated realurl information and use route enhancer

### PR DESCRIPTION
**Pull request by benjaminkott**
Releases: master, 9.1, 9.0
Fixes: #15 
Backports for 9.1 and 9.0 only information - keep the hooks.

### CODE REVIEW

**Comment by NeoBlack** [comment]
this is breaking, master only

**Comment by NeoBlack** [comment]
and it is not a bugfix but a task

**Comment by benjaminkott** [comment]
Why should this be breaking?

**Comment by NeoBlack** [comment]
do you know what I have installed in my setups?

**Comment by benjaminkott** [comment]
We agreed that we will leave the hooks inside the v9.x releases and only backport the notices.

**Pull request merged**
